name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use the appropriate Node.js version

      - name: Install dependencies
        run: npm ci  # Ensures clean install using package-lock.json

      - name: Grant execute permissions to Jest
        run: chmod +x node_modules/.bin/jest  # Fix permission issue

      - name: Run tests
        run: npm test
